hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from user_management.views import HomepageListView
# from wiki import views as wiki_views

urlpatterns = [
    path('', HomepageListView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('homepage/', include('user_management.urls')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace="wiki")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('commissions/', include('commissions.urls', namespace="commissions")),

]

hobbysite/merchstore/urls.py
from django.urls import path
from .views import (
    CartListView,
    MerchstoreDetailView,
    MerchstoreListView,
    ProductCreateView,
    ProductUpdateView,
    TransactionListView
)

urlpatterns = [
    path(
        'items',
        MerchstoreListView.as_view(),
        name='products'),
    path(
        'item/<int:pk>',
        MerchstoreDetailView.as_view(),
        name='product'),
    path(
        'item/<int:pk>/edit',
        ProductUpdateView.as_view(),
        name='product_update'),
    path('item/add', ProductCreateView.as_view(), name='product_add'),
    path('cart', CartListView.as_view(), name='cart'),
    path('transactions', TransactionListView.as_view(), name='transactions'),
]

app_name = 'Merchstore'

hobbysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('forum/', include('hobbysite.forum.urls')),
    path('', RedirectView.as_view(url='/forum/')),
]

ledger/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('recipes/list/', views.recipe_list, name='recipe_list'),
    path('recipe/1/', views.recipe_1, name='recipe_1'),
    path('recipe/2/', views.recipe_2, name='recipe_2'),
]

hobbysite/merchstore/models.py
from django.db import models
from user_management.models import Profile


class ProductType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = "Product Type"
        verbose_name_plural = "Product Types"


class Product(models.Model):
    name = models.CharField(max_length=255)
    product_type = models.ForeignKey(
        ProductType,
        on_delete=models.SET_NULL,
        null=True)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField()

    available = 'Available'
    on_sale = 'On Sale'
    out_of_stock = 'Out of Stock'
    status_choices = (
        (available, 'Available'),
        (on_sale, 'On Sale'),
        (out_of_stock, 'Out of Stock'),
    )
    status = models.CharField(choices=status_choices, max_length=255)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('Merchstore:product', args=[str(self.pk)])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = "Product"
        verbose_name_plural = "Products"


class Transaction(models.Model):
    '''Model definition for Transaction.'''
    buyer = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    amount = models.IntegerField()

    on_cart = 'On Cart'
    to_pay = 'To Pay'
    to_ship = 'To Ship'
    to_receive = 'To Receive'
    delivered = 'Delivered'
    status_choices = (
        (on_cart, 'On Cart'),
        (to_pay, 'To Pay'),
        (to_ship, 'To Ship'),
        (to_receive, 'To Receive'),
        (delivered, 'Delivered'),
    )
    status = models.CharField(choices=status_choices, max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        '''Meta definition for Transaction.'''

        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'

    def __str__(self):
        return self.buyer.name + ' - ' + self.product.name + ' (' + self.status + ')'

merchstore/models.py
from django.db import models


class ProductType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(max_length=255)
    product_type = models.ForeignKey(
        ProductType,
        on_delete=models.SET_NULL,
        null=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('merchstore:product', args=[str(self.pk)])

    class Meta:
        ordering = ['name']

hobbysite/merchstore/forms.py
from django import forms
from .models import Product, Transaction


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = (
            'name',
            'product_type',
            'owner',
            'description',
            'price',
            'stock',
            'status'
        )


class TransactionForm(forms.ModelForm):
    # buyer = forms.CharField(disabled=True)
    # product = forms.CharField(disabled=True)

    class Meta:
        model = Transaction
        fields = ('buyer', 'product', 'amount',)

hobbysite/merchstore/views.py
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from user_management.models import Profile

from .forms import ProductForm, TransactionForm
from .models import Product, Transaction


class MerchstoreListView(ListView):
    model = Product
    template_name = 'list_view.html'

    # Overloaded Function
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        all_products = Product.objects.order_by('name')

        if self.request.user.is_authenticated:
            user = Profile.objects.get(user=self.request.user)
            user_products = all_products.filter(
                owner=user
            )
            context['user_products'] = user_products

            all_products = all_products.exclude(
                owner=user
            )

        context['all_products'] = all_products
        return context


class MerchstoreDetailView(DetailView):
    model = Product
    template_name = 'detail_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = None
        if self.request.user.is_authenticated:
            user = Profile.objects.get(user=self.request.user)
            context['user'] = user

        context['transaction_form'] = TransactionForm(initial={
            'buyer': user,
            'product': context['object'],
            'amount': 1,
        })
        context['pk'] = self.kwargs['pk']
        return context

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        form = TransactionForm(request.POST)

        if form.is_valid():
            if request.user.is_authenticated:
                user = Profile.objects.get(user=self.request.user)
                transaction = form.save(commit=False)
                transaction.buyer = user
                transaction.product = product
                transaction.status = Transaction.on_cart
                transaction.save()
                if product.stock - transaction.amount < 0:
                    return self.get(request, *args, **kwargs)
                product.stock -= transaction.amount
                if product.stock <= 0:
                    product.status = Product.out_of_stock
                product.save()

                return redirect('Merchstore:cart')
            else:
                # !! should eventually redirect to the login page
                return redirect('admin:login')

        return self.get(request, *args, **kwargs)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'create_view.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        print(form.fields['owner'].__dir__())

        user = None
        if self.request.user.is_authenticated:
            user = Profile.objects.get(user=self.request.user)
        form.fields['owner'].initial = user
        form.fields['owner'].disabled = True
        form.fields['price'].initial = 0.00
        form.fields['stock'].initial = 1
        form.fields['status'].initial = Product.available
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = None
        if self.request.user.is_authenticated:
            user = Profile.objects.get(user=self.request.user)
            context['user'] = user
        return context


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'update_view.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['owner'].disabled = True
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context


class CartListView(ListView):
    model = Transaction
    template_name = 'cart_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = Profile.objects.get(user=self.request.user)
        transactions = Transaction.objects.filter(buyer=user)
        print(transactions)

        cart = {}
        for transaction in transactions:
            if not cart.__contains__(transaction.product.owner):
                cart[transaction.product.owner] = []
            cart[transaction.product.owner].append(transaction)

        context['cart'] = cart

        return context


class TransactionListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'transaction_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = Profile.objects.get(user=self.request.user)

        transactions = Transaction.objects.filter(product__owner=user)

        transaction_list = {}
        for transaction in transactions:
            if not transaction_list.__contains__(transaction.buyer):
                transaction_list[transaction.buyer] = []
            transaction_list[transaction.buyer].append(transaction)
            print(transaction.status)

        context['transaction_list'] = transaction_list

        return context

merchstore/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Product


class MerchstoreListView(ListView):
    model = Product
    template_name = 'product_list_view.html'


class MerchstoreDetailView(DetailView):
    model = Product
    template_name = 'product_detail_view.html'

hobbysite/merchstore/templates/cart_view.html
{% extends 'base.html' %}

{% block content %}
    {% for owner, transaction_list in cart.items %}
        <h4>{{owner.name}}</h4>
        <ul>
            {% for transaction in transaction_list %}
                <li>
                    {{ transaction.status }} <br>
                    {{ transaction.amount }} {{ transaction.product }}
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
{% endblock content %}

hobbysite/merchstore/templates/create_view.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'Merchstore:products' %}"><button>Back</button></a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">List Product</button>
    </form>
{% endblock content %}

hobbysite/merchstore/templates/detail_view.html
{% extends 'base.html' %}
{% block content %}
    <h1> Merch Store </h1>

    <a href="{% url 'Merchstore:products' %}"><button>Back</button></a>

    <h3> {{product.name}} </h3>
    <sub>by {{product.owner}}</sub>
    <ul>
        <li><b>Stock</b>: {{product.stock}}</li>
        <li><b>Price</b>: PHP {{product.price}}</li>
    </ul>

    {% if product.owner == user %}
        <p><a href="{% url 'Merchstore:product_update' pk %}">
            <button>Edit Product</button>
        </a></p>
    {% endif %}

    <b>{{product.product_type}}</b>
    <p>{{product.description}}</p>
    <p><b>{{product.status}}</b></p>

    <form method="post">
        {% csrf_token %}
        {{ transaction_form.as_p }}
        <button
            type="submit"
            {% if product.stock <= 0 or product.owner == user %}
                disabled
            {% endif %}
            >Purchase</button>
    </form>
    {% if error %}
        <p style="color:red">{{ error }}</p>
    {% endif %}
{% endblock content %}

hobbysite/merchstore/templates/list_view.html
{% extends 'base.html' %}
{% block content %}
    <h1>Merch Store</h1>

    {% if request.user.is_authenticated %}
        <p><a href="{% url 'Merchstore:product_add' %}">Create a New Product</a></p>
        <p><a href="{% url 'Merchstore:transactions' %}">Check Current Transactions</a></p>
        <h2>Your Products</h2>
        <ul>
            {% for product in user_products %}
                <li><a href="{{product.get_absolute_url}}">{{ product.name }}</a></li>
                {% empty %}
                <li>You have no products</li>
            {% endfor %}
        </ul>
    {% endif %}

    <h2>All Products</h2>
    <ul>
        {% for product in all_products %}
            <li><a href="{{product.get_absolute_url}}">{{product.name}}</a></li>
        {% empty %}
            <li>There are no products available</li>
        {% endfor %}
    </ul>
{% endblock content %}

hobbysite/merchstore/templates/transaction_view.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'Merchstore:products' %}"><button>Back</button></a>
    {% for buyer, transactions in transaction_list.items %}
        <h4>{{buyer.name}}</h4>
        <ul>
            {% for transaction in transactions %}
                <li>
                    {{ transaction.status }} <br>
                    {{ transaction.amount }} {{ transaction.product }}
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
{% endblock content %}

hobbysite/merchstore/templates/update_view.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'Merchstore:product' pk %}"><button>Back</button></a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Product</button>
    </form>
{% endblock content %}