hobbysite/blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('articles/', views.list_view, name='list_view'),
    path('articles/<int:id>/', views.detail_view, name='detail_view'),
    path('articles/category/<int:id>/', views.category_view, name='category_view')
]

app_name = 'blog'

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from user_management.views import HomepageListView
# from wiki import views as wiki_views

urlpatterns = [
    path('', HomepageListView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('homepage/', include('user_management.urls')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace="wiki")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('commissions/', include('commissions.urls', namespace="commissions")),

]

hobbysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('forum/', include('hobbysite.forum.urls')),
    path('', RedirectView.as_view(url='/forum/')),
]

ledger/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('recipes/list/', views.recipe_list, name='recipe_list'),
    path('recipe/1/', views.recipe_1, name='recipe_1'),
    path('recipe/2/', views.recipe_2, name='recipe_2'),
]

hobbysite/blog/models.py
from django.db import models
#from user_management.models import Profile


class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Article Categories"

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=255)
    #author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(ArticleCategory, null=True, on_delete=models.SET_NULL)
    entry = models.TextField()
    header_image = models.ImageField(upload_to='image/', blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    #author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_on']

hobbysite/blog/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category', 'entry', 'header_image']
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['entry']
        

hobbysite/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article, ArticleCategory, Comment
from .forms import ArticleForm, CommentForm

def list_view(request):
    articles = Article.objects.all()
    categories = ArticleCategory.objects.all()

    authored_articles = None
    non_authored_articles = articles

    if request.user.is_authenticated:
        authored_articles = articles.filter(author=request.user)
        non_authored_articles = articles.exclude(author=request.user)

    ctx = {
        'authored_articles': authored_articles,
        'articles': non_authored_articles,
        'categories': categories,
    }
    return render(request, 'blog/article_list.html', ctx)

def detail_view(request, id):
    article = Article.objects.get(id=id)
    comment = Comment.objects.filter(article=article).order_by('created_on')

    if request.method == 'POST' and request.user.is_authenticated:
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()

    ctx = {
        'article': article,
        'comment': comment,
    }

    return render(request, 'blog/article_detail.html', ctx)

def category_view(request, id):
    category = ArticleCategory.objects.get(id=id)
    articles = Article.objects.filter(category=category)
    return render(request, 'blog/category_list.html', {'category': category, 'articles': articles})

#@login_required
def add_article(request):
    form = ArticleForm()

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:list')
        
    ctx = {
        "form": form,
    }

    return render(request, "blog/add_article.html", ctx)

#@login_required
def edit_article(request, id):
    article = Article.objects.get(id=id)
    form = ArticleForm(instance=article)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', id=article.id)

    ctx = {
        'form': form,
        'article': article,
    } 

    return render(request, "blog/update_article.html", ctx)

hobbysite/blog/templates/blog/add_article.html
{% extends 'base.html' %}

{% block content %}
    <p><b>Add New Article</b></p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
    
{% endblock %}

hobbysite/blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    
    <br><h2>{{ article.title }}</h2>
    <b>Category:</b> {{ article.category.name }}
    <br><b>Created on:</b> {{ article.created_on }}
    <br><b>Updated on:</b> {{ article.updated_on }}
    <p><b>Description:</b> {{ article.entry }} </p>

    <p><a href="{% url 'blog:update_article' article.id %}">Edit this article</a></p>


    <p><a href="{% url 'blog:list_view' %}">Back</a></p>
{% endblock %}

hobbysite/blog/templates/blog/article_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Categories</h2>
    <ul>
        {% for category in categories %}
            <li>
                <b><a href="{% url 'blog:category_view' category.id %}">{{ category.name }}</a></li></b>
                > {{ category.description }}</li>
        {% endfor %}
    </ul>

    <h2>Articles</h2>
    <ul>
        {% for article in articles %}
            <li><a href="{% url 'blog:detail_view' article.id %}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

hobbysite/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
</head>
<body>
    <h1>This is the Seniors' Blog</h1>
    {% block content %}{% endblock %}
</body>
</html>

hobbysite/blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>{{ category.name }} Category</h2>
    <ul>
        {% for article in articles %}
            <li><a href="{% url 'blog:detail_view' article.id %}">{{ article.title }}</a></li>
        {% empty %}
            Sorry, no articles under this category.
        {% endfor %}
    </ul>
    <a href="{% url 'blog:list_view' %}">Back</a>
{% endblock %}

hobbysite/blog/templates/blog/update_article.html
{% extends 'base.html' %}

{% block content %}
    <p><b>Update Article</b></p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    
{% endblock %}