hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from user_management.views import HomepageListView
# from wiki import views as wiki_views

urlpatterns = [
    path('', HomepageListView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('homepage/', include('user_management.urls')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace="wiki")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('commissions/', include('commissions.urls', namespace="commissions")),

]

hobbysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('forum/', include('hobbysite.forum.urls')),
    path('', RedirectView.as_view(url='/forum/')),
]

hobbysite/wiki/urls.py
from django.urls import path
from . import views

app_name = 'wiki'

urlpatterns = [
    path('articles/', views.ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/add/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='article_update'),
]

ledger/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('recipes/list/', views.recipe_list, name='recipe_list'),
    path('recipe/1/', views.recipe_1, name='recipe_1'),
    path('recipe/2/', views.recipe_2, name='recipe_2'),
]

hobbysite/wiki/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
    
class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Article Categories'
    
    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='articles')
    category = models.ForeignKey(ArticleCategory, on_delete=models.SET_NULL, null=True, related_name='articles')
    entry = models.TextField()
    header_image = models.ImageField(upload_to='wiki_headers/', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_on']
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('wiki:article_detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='wiki_comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['created_on']
    
    def __str__(self):
        return f'Comment by {self.author} on {self.article.title}'

hobbysite/wiki/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Article, ArticleCategory, Comment
from .forms import ArticleForm, CommentForm

class ArticleListView(ListView):
    model = Article
    template_name = 'wiki/article_list.html'
    context_object_name = 'articles'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        categories = ArticleCategory.objects.order_by('name')
        context['categories'] = categories

        all_articles = Article.objects.order_by('-created_on')
        
        if self.request.user.is_authenticated:
            user_articles = all_articles.filter(author__user=self.request.user)
            context['user_articles'] = user_articles

            all_articles = all_articles.exclude(author__user=self.request.user)
        
        categorized_articles = {}
        for category in categories:
            categorized_articles[category] = all_articles.filter(category=category)
        
        context['categorized_articles'] = categorized_articles
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'wiki/article_detail.html'
    context_object_name = 'article'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.get_object()
        
        if article.category:
            context['related_articles'] = Article.objects.filter(
                category=article.category
            ).exclude(id=article.id)[:2]
        
        if self.request.user.is_authenticated:
            context['comment_form'] = CommentForm()
            
        context['comments'] = article.comments.all().order_by('-created_on')
        
        return context
    
    def post(self, request, *args, **kwargs):
        article = self.get_object()
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.article = article
                comment.author = request.user.profile
                comment.save()
                return redirect('wiki:article_detail', pk=article.pk)
        return self.get(request, *args, **kwargs)
    

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'wiki/article_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)
    

class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'wiki/article_form.html'
    
    def test_func(self):
        article = self.get_object()
        return article.author.user == self.request.user
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        return form

hobbysite/wiki/templates/wiki/article_detail.html
{% extends "wiki/base.html" %}

<h1>{{ article.title }}</h1>

{% if article.header_image %}
    <img src="{{ article.header_image.url }}" style="max-width:100%; height:auto;">
{% endif %}

<p>{{ article.entry }}</p>
<p>Category: {{ article.category }}</p>

{% if article.author == user %}
    <p><a href="{% url 'wiki:article_update' article.pk %}">Edit Article</a></p>
{% endif %}

<h3>More from {{ article.category }}</h3>
<ul>
    {% for related in related_articles %}
        <li><a href="{% url 'wiki:article_detail' related.pk %}">{{ related.title }}</a></li>
    {% empty %}
        <li>No related articles found.</li>
    {% endfor %}
</ul>

<h3>Comments</h3>

{% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit">Add Comment</button>
    </form>
{% else %}
    <p><a href="{% url 'login' %}">Login</a> to comment!</p>
{% endif %}

<ul>
    {% for comment in comments %}
        <li><strong>{{ comment.author }}</strong> ({{ comment.created_on }}): {{ comment.entry }}</li>
    {% empty %}
        <li>No comments yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'wiki:article_list' %}">Back to Articles</a>

hobbysite/wiki/templates/wiki/article_forms.html
{% extends "wiki/base.html" %}

<h1>{% if form.instance.pk %}Edit{% else %}Create{% endif %} Article</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% if form.instance.pk %}Update{% else %}Create{% endif %}</button>
</form>

hobbysite/wiki/templates/wiki/article_list.html
{% extends "wiki/base.html" %}

{% block content %}
<h1>Wiki Articles</h1>

{% if user.is_authenticated %}
    <h2>Your Articles</h2>
    <ul>
        {% for article in user_articles %}
            <li><a href="{% url 'wiki:article_detail' article.pk %}">{{ article.title }}</a></li>
        {% empty %}
            <li>You have no articles</li>
        {% endfor %}
    </ul>
{% endif %}

<h2>All Articles</h2>

{% for category, articles in categorized_articles.items %}

    {% if articles %}
        <h3>{{ category.name }}</h3>
        <ul>
            {% for article in articles %}
                <li><a href="{% url 'wiki:article_detail' article.pk %}">{{ article.title }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% empty %}
    <p>No articles found</p>
{% endfor %}
{% endblock %}

hobbysite/wiki/templates/wiki/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Hobby Site</title>
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'wiki:article_list' %}">Wiki</a>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>&copy; 2025</p>
    </footer>
</body>
</html>